require_relative 'models/tour'
require_relative 'models/tour_list'
require_relative 'models/tourist'
require_relative 'models/tourist_list'
require_relative 'models/scheme_types'
require_relative 'models/dry_result_forme_wrapper'
require_relative 'models/new_tour_schema'
require_relative 'models/tour_delete_schema'