require_relative 'models/book'
require_relative 'models/book_list'
require_relative 'models/book_form_schema'
require_relative 'models/dry_result_forme_wrapper'
require_relative 'models/scheme_types'
require_relative 'models/book_delete_schema'